'use strict';
// In-app help ("How it works"), three languages. Blocks: { h, p: [paragraphs], ul: [items], table: { head, rows } }.
const HELP = {
  en: [
    { h: 'What it does', p: ['Ticker Feed Builder downloads RSS feeds on a schedule and turns every feed into a fixed set of files for TV tickers and playout graphics: one line of text per headline, one line per description and one numbered JPG per story. The app runs in the tray, 24/7, and rewrites the files every few minutes.'] },
    { h: 'How to use it', ul: ['Create a profile. A profile is one destination: an output folder, a list of feeds and a refresh interval. Use several profiles if different screens read different folders.', 'Choose the output folder: the one your ticker or playout system reads.', 'Add feeds (name = folder name, URL, number of items). "Test" shows what the feed contains without writing anything.', 'Press "Run now" once and look at the folder, then leave it running. Closing the window keeps the app in the tray; use the tray menu to quit.'] },
    { h: 'What it writes', p: ['With the default format, for a feed named News:'], table: { head: ['File', 'Content'], rows: [['News_Title.Txt', 'One headline per line'], ['News_Description.Txt', 'One description per line, same order'], ['News/00001.JPG, 00002.JPG…', 'One JPG per story, same order'], ['News_metadata.json', 'Counters of the last run (can be switched off)']] } },
    { h: 'How lines and images stay in sync', ul: ['Story N is always line N of both text files and image N. Line breaks inside a text are removed, so a story can never take two lines.', 'An empty title or description becomes the "empty" text ("-" by default); a missing or unreadable image becomes the placeholder image. So the counts are always equal.', 'Files are written under a temporary name and renamed, so a player never reads a half-written file. A file whose content did not change is not touched.', 'If a feed cannot be downloaded, its existing files stay exactly as they were.', 'If the output folder is missing (unplugged drive, network share down) nothing is written and the folder is never created.'] },
    { h: 'Formats and NeMedia Morpheus', p: ['The default layout is the one produced by the original scripts that fed NeMedia Morpheus (file names, UTF-8 text, LF line ends, 5-digit JPG names). We did not read NeMedia documentation, so this is not verified against it. Other ticker systems may want other names, encodings or image sizes: all of them can be changed in "Output format".'] },
    { h: 'How often it checks, and what it downloads', ul: ['Every profile has a check interval (default 5 minutes); a feed can have its own interval in the table.', 'A check first asks the server whether the feed changed (ETag / Last-Modified); if the server says no, nothing else is downloaded. If the server cannot tell, the feed is downloaded and compared with the previous copy; when it is identical, images are not downloaded and no file is touched.', 'Only when something is new are images downloaded and files rewritten. If an image failed last time it is retried at the next check even if the feed is the same. If an output file was deleted or the settings changed, the feed is rebuilt.', 'Run now ignores the intervals and rebuilds everything. The Dashboard shows, for every feed, when it was last checked and when its files were last updated.'] },
    { h: 'Alerts', p: ['Because nobody watches the app, it can tell you: a desktop notification and/or Telegram when a feed fails several runs in a row, when an output folder disappears, and when things work again. Email is not offered: it would need an SMTP server and a password stored in the app.', 'To use Telegram create a bot with @BotFather, put its token in Settings and add the chat IDs that must receive the alerts.'] },
    { h: 'Certificate check', p: ['Some publishers serve feeds with a broken certificate. The option "Skip certificate check" lets that single feed download anyway: the connection is still encrypted, but the server is not verified. It is off by default and meant only for feeds you trust. The starter set turns it on for the Adnkronos feeds, as the original scripts did.'] },
    { h: 'Validation', table: { head: ['Reference', 'What it checks', 'Result', 'How to repeat'], rows: [
      ['Automated tests (16)', 'Text cleaning, RSS/Atom parsing, line/image sync, empty values, orphan removal, unchanged files, failure keeps old files, scheduler, alerts', 'Pass', 'npm test'],
      ['Original Python script, 2026-10-08, 8 live feeds', 'Same titles and descriptions as the original for the same feeds', '14 of 16 text files identical; 2 differ because the feeds changed between the two runs (shifted stories). One title carried an invisible BOM character in the original; the new app removes it', 'Run both on the same folder and compare'],
      ['Image counts', 'Number of images per feed equals the original', 'Equal for all 8 feeds', 'Same as above']] },
      after: ['Not validated: playback in NeMedia Morpheus or any other ticker system, Windows paths and drives, long-running behaviour over days, Windows-1252 output beyond a unit test. This is not a certified tool.'] },
    { h: 'Privacy', p: ['The app contacts only the feed and image addresses you configure, GitHub (optional update check) and Telegram (only if you enable it). No analytics, no account. Settings and logs stay on this computer; the Telegram token is encrypted with the system keystore when available.'] },
    { h: 'Limits', ul: ['Images are converted with a pure-JavaScript library: JPEG, PNG, GIF, BMP and TIFF are supported; WebP and AVIF are not (the story gets the placeholder).', 'Image addresses on the local network are ignored for feeds on the public internet.', 'The computer must stay on and awake; the option "Keep the computer awake" helps.'] }
  ],
  it: [
    { h: 'Cosa fa', p: ['Ticker Feed Builder scarica i feed RSS a intervalli regolari e trasforma ogni feed in un insieme fisso di file per i ticker TV e le grafiche di playout: una riga di testo per titolo, una per descrizione e un JPG numerato per notizia. L\'app gira nella barra di sistema, 24 ore su 24, e riscrive i file ogni pochi minuti.'] },
    { h: 'Come si usa', ul: ['Crea un profilo. Un profilo è una destinazione: una cartella di output, un elenco di feed e un intervallo di aggiornamento. Usa più profili se schermi diversi leggono cartelle diverse.', 'Scegli la cartella di output: quella che legge il tuo sistema di ticker o playout.', 'Aggiungi i feed (nome = nome della cartella, URL, numero di notizie). "Prova" mostra cosa contiene il feed senza scrivere nulla.', 'Premi "Esegui ora" una volta e controlla la cartella, poi lascia andare. Chiudendo la finestra l\'app resta nella barra di sistema; per uscire usa il menu dell\'icona.'] },
    { h: 'Cosa scrive', p: ['Con il formato predefinito, per un feed chiamato News:'], table: { head: ['File', 'Contenuto'], rows: [['News_Title.Txt', 'Un titolo per riga'], ['News_Description.Txt', 'Una descrizione per riga, stesso ordine'], ['News/00001.JPG, 00002.JPG…', 'Un JPG per notizia, stesso ordine'], ['News_metadata.json', 'Contatori dell\'ultimo giro (si può disattivare)']] } },
    { h: 'Come restano allineati testi e immagini', ul: ['La notizia N è sempre la riga N di entrambi i file di testo e l\'immagine N. Gli a capo dentro un testo vengono tolti, quindi una notizia non può mai occupare due righe.', 'Un titolo o una descrizione vuoti diventano il testo "vuoto" ("-" di default); un\'immagine mancante o illeggibile diventa l\'immagine segnaposto. I conteggi quindi coincidono sempre.', 'I file sono scritti con un nome temporaneo e poi rinominati, così un player non legge mai un file a metà. Un file il cui contenuto non è cambiato non viene toccato.', 'Se un feed non si scarica, i suoi file esistenti restano com\'erano.', 'Se la cartella di output manca (disco scollegato, condivisione di rete non raggiungibile) non viene scritto nulla e la cartella non viene mai creata.'] },
    { h: 'Formati e NeMedia Morpheus', p: ['La struttura predefinita è quella prodotta dagli script originali che alimentavano NeMedia Morpheus (nomi dei file, testo UTF-8, fine riga LF, nomi JPG a 5 cifre). Non abbiamo letto documentazione NeMedia, quindi non è verificata su di essa. Altri sistemi di ticker possono volere nomi, codifiche o dimensioni diverse: tutto si cambia in "Formato di output".'] },
    { h: 'Ogni quanto controlla e cosa scarica', ul: ['Ogni profilo ha un intervallo di controllo (predefinito 5 minuti); un feed può avere un intervallo suo nella tabella.', 'Un controllo chiede prima al server se il feed è cambiato (ETag / Last-Modified); se il server dice di no, non si scarica altro. Se il server non sa dirlo, il feed viene scaricato e confrontato con la copia precedente; se è identico, le immagini non vengono scaricate e nessun file viene toccato.', 'Solo se c\'è qualcosa di nuovo si scaricano le immagini e si riscrivono i file. Se un\'immagine è fallita l\'ultima volta viene riprovata al controllo successivo anche se il feed è uguale. Se un file di output è stato cancellato o le impostazioni sono cambiate, il feed viene ricostruito.', 'Esegui ora ignora gli intervalli e ricostruisce tutto. La Dashboard mostra, per ogni feed, quando è stato controllato l\'ultima volta e quando i suoi file sono stati aggiornati.'] },
    { h: 'Avvisi', p: ['Poiché nessuno guarda l\'app, è lei a avvisarti: notifica sul desktop e/o Telegram quando un feed fallisce più giri di fila, quando una cartella di output sparisce e quando tutto torna a funzionare. L\'email non è prevista: richiederebbe un server SMTP e una password salvata nell\'app.', 'Per usare Telegram crea un bot con @BotFather, inserisci il token nelle Impostazioni e aggiungi i chat ID che devono ricevere gli avvisi.'] },
    { h: 'Controllo del certificato', p: ['Alcuni editori servono i feed con un certificato difettoso. L\'opzione "Ignora controllo certificato" permette a quel solo feed di scaricarsi comunque: la connessione resta cifrata, ma il server non viene verificato. È disattivata di default e pensata solo per feed di cui ti fidi. Il set iniziale la attiva per i feed Adnkronos, come facevano gli script originali.'] },
    { h: 'Validazione', table: { head: ['Riferimento', 'Cosa verifica', 'Risultato', 'Come rifarla'], rows: [
      ['Test automatici (16)', 'Pulizia del testo, lettura RSS/Atom, allineamento righe/immagini, valori vuoti, rimozione immagini orfane, file invariati, il guasto conserva i vecchi file, pianificatore, avvisi', 'Superati', 'npm test'],
      ['Script Python originale, 2026-10-08, 8 feed reali', 'Stessi titoli e descrizioni dell\'originale per gli stessi feed', '14 file di testo su 16 identici; 2 differiscono perché i feed sono cambiati fra le due esecuzioni (notizie scalate). Un titolo portava un carattere BOM invisibile nell\'originale; la nuova app lo elimina', 'Eseguire entrambi sulla stessa cartella e confrontare'],
      ['Numero di immagini', 'Il numero di immagini per feed coincide con l\'originale', 'Uguale per tutti e 8 i feed', 'Come sopra']] },
      after: ['Non validato: riproduzione in NeMedia Morpheus o in altri sistemi di ticker, percorsi e unità di Windows, funzionamento continuo per giorni, uscita Windows-1252 oltre a un test unitario. Non è uno strumento certificato.'] },
    { h: 'Privacy', p: ['L\'app contatta solo gli indirizzi di feed e immagini che configuri, GitHub (controllo aggiornamenti, facoltativo) e Telegram (solo se lo attivi). Nessuna statistica, nessun account. Impostazioni e log restano su questo computer; il token Telegram è cifrato con il portachiavi del sistema quando disponibile.'] },
    { h: 'Limiti', ul: ['Le immagini sono convertite con una libreria JavaScript pura: JPEG, PNG, GIF, BMP e TIFF sono supportati; WebP e AVIF no (la notizia riceve il segnaposto).', 'Gli indirizzi di immagini sulla rete locale vengono ignorati per i feed su internet pubblico.', 'Il computer deve restare acceso e sveglio; l\'opzione "Tieni il computer sveglio" aiuta.'] }
  ],
  es: [
    { h: 'Qué hace', p: ['Ticker Feed Builder descarga feeds RSS de forma programada y convierte cada feed en un conjunto fijo de archivos para tickers de TV y gráficos de emisión: una línea de texto por titular, una por descripción y un JPG numerado por noticia. La app funciona en la bandeja, 24 horas, y reescribe los archivos cada pocos minutos.'] },
    { h: 'Cómo se usa', ul: ['Crea un perfil. Un perfil es un destino: una carpeta de salida, una lista de feeds y un intervalo de actualización. Usa varios perfiles si pantallas distintas leen carpetas distintas.', 'Elige la carpeta de salida: la que lee tu sistema de ticker o de emisión.', 'Añade feeds (nombre = nombre de carpeta, URL, número de noticias). "Probar" muestra qué contiene el feed sin escribir nada.', 'Pulsa "Ejecutar ahora" una vez y mira la carpeta; luego déjalo funcionando. Al cerrar la ventana la app sigue en la bandeja; para salir usa el menú del icono.'] },
    { h: 'Qué escribe', p: ['Con el formato por defecto, para un feed llamado News:'], table: { head: ['Archivo', 'Contenido'], rows: [['News_Title.Txt', 'Un titular por línea'], ['News_Description.Txt', 'Una descripción por línea, mismo orden'], ['News/00001.JPG, 00002.JPG…', 'Un JPG por noticia, mismo orden'], ['News_metadata.json', 'Contadores de la última ejecución (se puede desactivar)']] } },
    { h: 'Cómo se mantienen sincronizados textos e imágenes', ul: ['La noticia N es siempre la línea N de ambos archivos de texto y la imagen N. Los saltos de línea dentro de un texto se eliminan, así que una noticia nunca ocupa dos líneas.', 'Un título o descripción vacíos pasan a ser el texto "vacío" ("-" por defecto); una imagen ausente o ilegible pasa a ser la imagen de relleno. Los recuentos siempre coinciden.', 'Los archivos se escriben con un nombre temporal y se renombran, así un reproductor nunca lee un archivo a medias. Un archivo cuyo contenido no cambió no se toca.', 'Si un feed no se puede descargar, sus archivos existentes quedan como estaban.', 'Si falta la carpeta de salida (disco desconectado, recurso de red caído) no se escribe nada y la carpeta nunca se crea.'] },
    { h: 'Formatos y NeMedia Morpheus', p: ['La estructura por defecto es la que producían los scripts originales que alimentaban NeMedia Morpheus (nombres de archivo, texto UTF-8, fin de línea LF, nombres JPG de 5 cifras). No hemos leído documentación de NeMedia, así que no está verificada con ella. Otros sistemas de ticker pueden querer otros nombres, codificaciones o tamaños: todo se cambia en "Formato de salida".'] },
    { h: 'Cada cuánto comprueba y qué descarga', ul: ['Cada perfil tiene un intervalo de comprobación (por defecto 5 minutos); un feed puede tener su propio intervalo en la tabla.', 'Una comprobación pregunta primero al servidor si el feed cambió (ETag / Last-Modified); si dice que no, no se descarga nada más. Si el servidor no sabe decirlo, el feed se descarga y se compara con la copia anterior; si es idéntico, no se descargan imágenes y no se toca ningún archivo.', 'Solo si hay algo nuevo se descargan las imágenes y se reescriben los archivos. Si una imagen falló la última vez se reintenta en la siguiente comprobación aunque el feed sea el mismo. Si se borró un archivo de salida o cambiaron los ajustes, el feed se reconstruye.', 'Ejecutar ahora ignora los intervalos y reconstruye todo. El Panel muestra, para cada feed, cuándo se comprobó por última vez y cuándo se actualizaron sus archivos.'] },
    { h: 'Alertas', p: ['Como nadie mira la app, ella te avisa: notificación de escritorio y/o Telegram cuando un feed falla varias ejecuciones seguidas, cuando desaparece una carpeta de salida y cuando todo vuelve a funcionar. El correo no se ofrece: requeriría un servidor SMTP y una contraseña guardada en la app.', 'Para usar Telegram crea un bot con @BotFather, pon su token en Ajustes y añade los chat ID que deben recibir las alertas.'] },
    { h: 'Comprobación del certificado', p: ['Algunos editores sirven feeds con un certificado defectuoso. La opción "Omitir comprobación del certificado" permite que ese feed se descargue igualmente: la conexión sigue cifrada, pero el servidor no se verifica. Está desactivada por defecto y pensada solo para feeds de confianza. El conjunto inicial la activa en los feeds de Adnkronos, como hacían los scripts originales.'] },
    { h: 'Validación', table: { head: ['Referencia', 'Qué comprueba', 'Resultado', 'Cómo repetirla'], rows: [
      ['Pruebas automáticas (16)', 'Limpieza de texto, lectura RSS/Atom, sincronía líneas/imágenes, valores vacíos, eliminación de imágenes huérfanas, archivos sin cambios, el fallo conserva los archivos antiguos, programador, alertas', 'Superadas', 'npm test'],
      ['Script Python original, 2026-10-08, 8 feeds reales', 'Mismos títulos y descripciones que el original para los mismos feeds', '14 de 16 archivos de texto idénticos; 2 difieren porque los feeds cambiaron entre las dos ejecuciones (noticias desplazadas). Un título llevaba un carácter BOM invisible en el original; la nueva app lo elimina', 'Ejecutar ambos sobre la misma carpeta y comparar'],
      ['Número de imágenes', 'El número de imágenes por feed coincide con el original', 'Igual en los 8 feeds', 'Como arriba']] },
      after: ['No validado: reproducción en NeMedia Morpheus u otros sistemas de ticker, rutas y unidades de Windows, funcionamiento continuo durante días, salida Windows-1252 más allá de una prueba unitaria. No es una herramienta certificada.'] },
    { h: 'Privacidad', p: ['La app solo contacta las direcciones de feeds e imágenes que configuras, GitHub (comprobación de actualizaciones, opcional) y Telegram (solo si lo activas). Sin analíticas ni cuenta. Ajustes y logs se quedan en este ordenador; el token de Telegram se cifra con el llavero del sistema cuando está disponible.'] },
    { h: 'Límites', ul: ['Las imágenes se convierten con una biblioteca JavaScript pura: JPEG, PNG, GIF, BMP y TIFF son compatibles; WebP y AVIF no (la noticia recibe la imagen de relleno).', 'Las direcciones de imágenes de la red local se ignoran en feeds de internet público.', 'El ordenador debe seguir encendido y despierto; la opción "Mantener el ordenador despierto" ayuda.'] }
  ]
};
