'use strict';
// In-app help ("How it works"), three languages. Blocks: { h, p: [paragraphs], ul: [items], table: { head, rows } }.
const HELP = {
  en: [
    { h: 'What it does', p: ['Ticker Feed Builder downloads RSS feeds on a schedule and turns every feed into a fixed set of files for TV tickers and playout graphics: one line of text per headline, one line per description and one numbered JPG per story. The app runs in the tray, 24/7, and rewrites the files every few minutes.'] },
    { h: 'How to use it', ul: ['Create a profile. A profile is one destination: an output folder, a list of feeds and a refresh interval. Use several profiles if different screens read different folders.', 'Choose the output folder: the one your ticker or playout system reads.', 'Add feeds (name = folder name, URL, number of items). "Test" shows what the feed contains without writing anything.', 'Press "Run now" once and look at the folder, then leave it running. Closing the window keeps the app in the tray; use the tray menu to quit.'] },
    { h: 'What it writes', p: ['With the default format, for a feed named News:'], table: { head: ['File', 'Content'], rows: [['News_Title.Txt', 'One headline per line'], ['News_Description.Txt', 'One description per line, same order'], ['News/00001.JPG, 00002.JPG…', 'One JPG per story, same order'], ['News_metadata.json', 'Counters of the last run (can be switched off)']] } },
    { h: 'How lines and images stay in sync', ul: ['Story N is always line N of both text files and image N. Line breaks inside a text are removed, so a story can never take two lines.', 'An empty title or description becomes the "empty" text ("-" by default); a missing or unreadable image becomes the placeholder image. So the counts are always equal.', 'Files are written under a temporary name and renamed, so a player never reads a half-written file. A file whose content did not change is not touched.', 'If a feed cannot be downloaded, its existing files stay exactly as they were.', 'If the output folder is missing (unplugged drive, network share down) nothing is written and the folder is never created.'] },
    { h: 'Formats and NeMedia Morpheus', p: ['The default layout is the one produced by the original scripts that fed NeMedia Morpheus (file names, UTF-8 text, LF line ends, 5-digit JPG names). We did not read NeMedia documentation, so this is not verified against it. Other ticker systems may want other names, encodings or image sizes: all of them can be changed in "Output format".'] },
    { h: 'How often it checks, and what it downloads', ul: ['Every profile has a check interval (default 5 minutes); a feed can have its own interval in the table.', 'A check first asks the server whether the feed changed (ETag / Last-Modified); if the server says no, nothing else is downloaded. If the server cannot tell, the feed is downloaded and compared with the previous copy; when it is identical, images are not downloaded and no file is touched.', 'Only when something is new are images downloaded and files rewritten. If an image failed last time it is retried at the next check even if the feed is the same. If an output file was deleted or the settings changed, the feed is rebuilt.', 'Run now ignores the intervals and rebuilds everything. The Dashboard shows, for every feed, when it was last checked and when its files were last updated.'] },
    { h: 'Choosing the stories: filters, order, merged feeds', ul: ['In a feed\'s Options you can keep only the stories containing certain words, leave out the ones containing others (capital letters and accents do not matter), look in the title only or in title and description, remove stories with the same title and order them newest first. Filters work before the limit: with 10 items and some stories filtered out you still get 10, if the feed has them.', 'A profile can also leave out a story already used by an earlier feed of the same profile (Schedule & options).', 'A merged feed ("+ Add merged feed") puts the latest stories of several feeds of the profile in one folder, newest first and without duplicates: useful for a mixed "Latest news" ticker. It is rebuilt when one of its sources has something new.', 'Test shows the stories exactly as they would be written (file names, title and description lines, image) and can show the feed as it is, without filters.'] },
    { h: 'Time windows', p: ['In Schedule & options a profile can be checked only inside certain hours and days, for example 06:00 to 24:00, or every 2 minutes during the evening news and every 15 at night. Outside the windows nothing is checked and the files stay as they are. From = To means the whole day; From later than To continues past midnight. "Run now" always works.'] },
    { h: 'Frozen feeds, summary and file check', ul: ['Frozen feed alert: if a feed answers but has had no new stories for the number of hours you set (per profile or per feed), you are alerted, and again when it recovers. It catches a ticker that looks fine but is frozen. 0 = off.', 'Daily summary: at the times you choose, a message on the enabled channels (Telegram, email) with feeds OK, problems and the last update of each profile. "Send summary now" tries it. It is off by default.', 'File check: after writing, the app reads the files back and checks that the title and description files have as many lines as there are stories and that every image is a real JPEG. If not, or if a player holds a file open so that it cannot be replaced, the feed counts as failed and the alert rules apply. It can be switched off per profile.', 'Memory between restarts: the app remembers what each feed looked like, so after a restart an unchanged feed is not rebuilt and no image is downloaded again. It can be switched off in Settings.'] },
    { h: 'Headless mode', p: ['The same engine can run without a window, for a server or a machine that must keep the ticker updated after a restart before anyone logs in: export the settings, then start it from the command line (the exact commands are in Settings, section Headless mode). It uses the same schedules, filters, alerts (Telegram and email) and daily summary. Secrets are not in the exported file: set TFB_TELEGRAM_TOKEN and TFB_SMTP_PASS in the environment. On Windows start it with Task Scheduler at startup ("run whether the user is logged on or not"); on Linux with a systemd service. --once runs everything one time and exits with 0 (all fine), 1 (a problem) or 2 (unusable settings).'] },
    { h: 'Alerts', p: ['Because nobody watches the app, it can tell you: a desktop notification, Telegram and/or email when a feed fails several runs in a row, when an output folder disappears, and when things work again. Telegram and email accept several recipients.', 'To use Telegram create a bot with @BotFather, put its token in Settings and add the chat IDs that must receive the alerts. For email enter your SMTP server, user, password, sender and the recipients (one per line); the password stays on this computer, encrypted with the system keystore when available, and the connection must be encrypted when a user name is used. Use the test buttons in Settings to check each channel.', 'New version: if Telegram or email is on, the app also tells you once for each new release published on GitHub (Settings, Updates; it checks every 6 hours, even with the window closed). Switch it off there if you do not want it.', 'On the dashboard each feed shows its last checks as small bars (green = new stories, grey = no change, red = failed, since the app started), and every profile says in words whether it is OK, partial or has a problem.'] },
    { h: 'Feeds and publishers\' terms', p: ['A feed that is free to download is not necessarily free to broadcast. Publishers usually offer RSS for personal reading; showing their headlines publicly on TV, screens or websites normally needs an agreement with them. The responsibility is yours, not the app\'s, and this is not legal advice.', 'The app ships with no feeds. Two publishers whose RSS pages were read on 8 October 2026 (paraphrased; read the current page before you rely on it):'], table: { head: ['Publisher', 'What its RSS page says', 'Page'], rows: [
      ['ANSA', 'Non-commercial use by individuals and non-profit organisations, only to view the feeds in RSS reader programs. Using them to publish the latest headlines on websites or blogs is not allowed. Any other use must be requested and expressly authorised.', 'ansa.it/sito/static/ansa_rss.html'],
      ['Adnkronos', 'Non-commercial use by individuals and non-profit organisations. The feeds may not be made public: not for websites, blogs, outdoor communication systems or any other means that spreads the news publicly, unless there is a prior agreement with Adnkronos.', 'adnkronos.com/rss']] },
      after: ['Both pages list their feeds (by section, e.g. politics, foreign news, sport): use them as examples of what to ask for in an agreement. For any other publisher, read its terms the same way. Before putting a feed on air, get the publisher\'s agreement; the feed URL is then added in the Feeds tab.'] },
    { h: 'Certificate check', p: ['Some publishers serve feeds with a broken certificate. The option "Skip certificate check" lets that single feed download anyway: the connection is still encrypted, but the server is not verified. It is off by default and meant only for feeds you trust.'] },
    { h: 'Validation', table: { head: ['Reference', 'What it checks', 'Result', 'How to repeat'], rows: [
      ['Automated tests (35)', 'Text cleaning, RSS/Atom parsing, line/image sync, empty values, orphan removal, unchanged files, failure keeps old files, scheduler, alerts', 'Pass', 'npm test'],
      ['Original Python script, 2026-10-08, 8 live feeds', 'Same titles and descriptions as the original for the same feeds', '14 of 16 text files identical; 2 differ because the feeds changed between the two runs (shifted stories). One title carried an invisible BOM character in the original; the new app removes it', 'Run both on the same folder and compare'],
      ['Image counts', 'Number of images per feed equals the original', 'Equal for all 8 feeds', 'Same as above']] },
      after: ['Not validated: playback in NeMedia Morpheus or any other ticker system, Windows paths and drives, long-running behaviour over days, Windows-1252 output beyond a unit test. This is not a certified tool.'] },
    { h: 'Privacy', p: ['The app contacts only the feed and image addresses you configure, GitHub (optional update check) and Telegram (only if you enable it). No analytics, no account. Settings and logs stay on this computer; the Telegram token is encrypted with the system keystore when available.'] },
    { h: 'Limits', ul: ['Images are converted to JPEG: JPEG, PNG, GIF, BMP and TIFF with a JavaScript library, WebP and AVIF with WebAssembly decoders (a very large AVIF can take a few seconds). If conversion is switched off in Output format, or an image cannot be read, the story gets the placeholder.', 'Image addresses on the local network are ignored for feeds on the public internet.', 'The computer must stay on and awake; the option "Keep the computer awake" helps.'] }
  ],
  it: [
    { h: 'Cosa fa', p: ['Ticker Feed Builder scarica i feed RSS a intervalli regolari e trasforma ogni feed in un insieme fisso di file per i ticker TV e le grafiche di playout: una riga di testo per titolo, una per descrizione e un JPG numerato per notizia. L\'app gira nella barra di sistema, 24 ore su 24, e riscrive i file ogni pochi minuti.'] },
    { h: 'Come si usa', ul: ['Crea un profilo. Un profilo è una destinazione: una cartella di output, un elenco di feed e un intervallo di aggiornamento. Usa più profili se schermi diversi leggono cartelle diverse.', 'Scegli la cartella di output: quella che legge il tuo sistema di ticker o playout.', 'Aggiungi i feed (nome = nome della cartella, URL, numero di notizie). "Prova" mostra cosa contiene il feed senza scrivere nulla.', 'Premi "Esegui ora" una volta e controlla la cartella, poi lascia andare. Chiudendo la finestra l\'app resta nella barra di sistema; per uscire usa il menu dell\'icona.'] },
    { h: 'Cosa scrive', p: ['Con il formato predefinito, per un feed chiamato News:'], table: { head: ['File', 'Contenuto'], rows: [['News_Title.Txt', 'Un titolo per riga'], ['News_Description.Txt', 'Una descrizione per riga, stesso ordine'], ['News/00001.JPG, 00002.JPG…', 'Un JPG per notizia, stesso ordine'], ['News_metadata.json', 'Contatori dell\'ultimo giro (si può disattivare)']] } },
    { h: 'Come restano allineati testi e immagini', ul: ['La notizia N è sempre la riga N di entrambi i file di testo e l\'immagine N. Gli a capo dentro un testo vengono tolti, quindi una notizia non può mai occupare due righe.', 'Un titolo o una descrizione vuoti diventano il testo "vuoto" ("-" di default); un\'immagine mancante o illeggibile diventa l\'immagine segnaposto. I conteggi quindi coincidono sempre.', 'I file sono scritti con un nome temporaneo e poi rinominati, così un player non legge mai un file a metà. Un file il cui contenuto non è cambiato non viene toccato.', 'Se un feed non si scarica, i suoi file esistenti restano com\'erano.', 'Se la cartella di output manca (disco scollegato, condivisione di rete non raggiungibile) non viene scritto nulla e la cartella non viene mai creata.'] },
    { h: 'Formati e NeMedia Morpheus', p: ['La struttura predefinita è quella prodotta dagli script originali che alimentavano NeMedia Morpheus (nomi dei file, testo UTF-8, fine riga LF, nomi JPG a 5 cifre). Non abbiamo letto documentazione NeMedia, quindi non è verificata su di essa. Altri sistemi di ticker possono volere nomi, codifiche o dimensioni diverse: tutto si cambia in "Formato di output".'] },
    { h: 'Ogni quanto controlla e cosa scarica', ul: ['Ogni profilo ha un intervallo di controllo (predefinito 5 minuti); un feed può avere un intervallo suo nella tabella.', 'Un controllo chiede prima al server se il feed è cambiato (ETag / Last-Modified); se il server dice di no, non si scarica altro. Se il server non sa dirlo, il feed viene scaricato e confrontato con la copia precedente; se è identico, le immagini non vengono scaricate e nessun file viene toccato.', 'Solo se c\'è qualcosa di nuovo si scaricano le immagini e si riscrivono i file. Se un\'immagine è fallita l\'ultima volta viene riprovata al controllo successivo anche se il feed è uguale. Se un file di output è stato cancellato o le impostazioni sono cambiate, il feed viene ricostruito.', 'Esegui ora ignora gli intervalli e ricostruisce tutto. La Dashboard mostra, per ogni feed, quando è stato controllato l\'ultima volta e quando i suoi file sono stati aggiornati.'] },
    { h: 'Scegliere le notizie: filtri, ordine, feed uniti', ul: ['Nelle Opzioni di un feed puoi tenere solo le notizie che contengono certe parole, escludere quelle che ne contengono altre (maiuscole e accenti non contano), cercare solo nel titolo o in titolo e descrizione, togliere le notizie con lo stesso titolo e ordinarle dalla più recente. I filtri agiscono prima del limite: con 10 notizie e alcune escluse ne ottieni comunque 10, se il feed le ha.', 'Un profilo può anche escludere una notizia già usata da un feed precedente dello stesso profilo (Pianificazione e opzioni).', 'Un feed unito ("+ Aggiungi feed unito") mette in una cartella le ultime notizie di più feed del profilo, le più recenti per prime e senza doppioni: utile per un ticker misto "Ultime notizie". Si ricostruisce quando una delle sue fonti ha qualcosa di nuovo.', 'Prova mostra le notizie esattamente come verrebbero scritte (nomi dei file, righe di titolo e descrizione, immagine) e può mostrare il feed così com\'è, senza filtri.'] },
    { h: 'Fasce orarie', p: ['In Pianificazione e opzioni un profilo può essere controllato solo in certe ore e giorni, ad esempio dalle 06:00 alle 24:00, oppure ogni 2 minuti durante il telegiornale e ogni 15 di notte. Fuori dalle fasce non si controlla nulla e i file restano come sono. Da = A significa tutto il giorno; Da dopo A prosegue oltre la mezzanotte. "Esegui ora" funziona sempre.'] },
    { h: 'Feed fermi, riepilogo e controllo dei file', ul: ['Avviso di feed fermo: se un feed risponde ma non ha notizie nuove da tante ore quante ne imposti (per profilo o per feed), ricevi un avviso, e un altro quando riparte. Scopre un ticker che sembra a posto ma è fermo. 0 = disattivato.', 'Riepilogo giornaliero: agli orari che scegli, un messaggio sui canali attivi (Telegram, email) con feed OK, problemi e ultimo aggiornamento di ogni profilo. "Invia il riepilogo ora" lo prova. È disattivato di default.', 'Controllo dei file: dopo la scrittura l\'app rilegge i file e verifica che i file di titoli e descrizioni abbiano tante righe quante sono le notizie e che ogni immagine sia un vero JPEG. Se non è così, o se un player tiene aperto un file e non si può sostituire, il feed conta come fallito e valgono le regole degli avvisi. Si può disattivare per profilo.', 'Memoria fra i riavvii: l\'app ricorda com\'era ogni feed, così dopo un riavvio un feed invariato non viene ricostruito e non si riscarica nessuna immagine. Si può disattivare nelle Impostazioni.'] },
    { h: 'Modalità senza finestra', p: ['Lo stesso motore può girare senza finestra, per un server o una macchina che deve tenere aggiornato il ticker dopo un riavvio prima che qualcuno faccia login: esporta le impostazioni, poi avvialo da riga di comando (i comandi esatti sono nelle Impostazioni, sezione Modalità senza finestra). Usa le stesse pianificazioni, filtri, avvisi (Telegram ed email) e riepilogo giornaliero. I segreti non sono nel file esportato: imposta TFB_TELEGRAM_TOKEN e TFB_SMTP_PASS nell\'ambiente. Su Windows avviala con l\'Utilità di pianificazione all\'avvio ("esegui indipendentemente dalla connessione dell\'utente"); su Linux con un servizio systemd. --once esegue tutto una volta ed esce con 0 (tutto bene), 1 (un problema) o 2 (impostazioni inutilizzabili).'] },
    { h: 'Avvisi', p: ['Poiché nessuno guarda l\'app, è lei a avvisarti: notifica sul desktop, Telegram e/o email quando un feed fallisce più giri di fila, quando una cartella di output sparisce e quando tutto torna a funzionare. Telegram ed email accettano più destinatari.', 'Per usare Telegram crea un bot con @BotFather, inserisci il token nelle Impostazioni e aggiungi i chat ID che devono ricevere gli avvisi. Per l\'email inserisci server SMTP, utente, password, mittente e i destinatari (uno per riga); la password resta su questo computer, cifrata con il portachiavi del sistema quando disponibile, e con un nome utente la connessione deve essere cifrata. Usa i pulsanti di prova nelle Impostazioni per controllare ogni canale.', 'Nuova versione: se Telegram o l\'email sono attivi, l\'app ti avvisa anche una volta per ogni nuova release pubblicata su GitHub (Impostazioni, Aggiornamenti; controlla ogni 6 ore, anche a finestra chiusa). Lì puoi disattivare l\'avviso.', 'Nella dashboard ogni feed mostra gli ultimi controlli come piccole barre (verde = notizie nuove, grigio = nessun cambiamento, rosso = fallito, dall\'avvio dell\'app) e ogni profilo dice a parole se è OK, parziale o con un problema.'] },
    { h: 'Feed e condizioni degli editori', p: ['Un feed scaricabile liberamente non è per forza trasmissibile. Gli editori di solito offrono gli RSS per lettura personale; mostrare i loro titoli in pubblico su TV, schermi o siti richiede normalmente un accordo con loro. La responsabilità è tua, non dell\'app, e questa non è una consulenza legale.', 'L\'app non include feed. Due editori le cui pagine RSS sono state lette l\'8 ottobre 2026 (parafrasi; leggi la pagina attuale prima di fidarti):'], table: { head: ['Editore', 'Cosa dice la sua pagina RSS', 'Pagina'], rows: [
      ['ANSA', 'Uso non commerciale da parte di privati e organizzazioni senza scopo di lucro, solo per visualizzare i feed in programmi lettori RSS. Non è consentito usarli per pubblicare gli ultimi titoli su siti web o blog. Ogni altro impiego va richiesto e autorizzato espressamente.', 'ansa.it/sito/static/ansa_rss.html'],
      ['Adnkronos', 'Uso non commerciale da parte di privati e organizzazioni senza scopo di lucro. I feed non possono essere resi pubblici: non per siti web, blog, sistemi di comunicazione outdoor o altri mezzi che diffondano le notizie in pubblico, salvo accordo preventivo con Adnkronos.', 'adnkronos.com/rss']] },
      after: ['Entrambe le pagine elencano i loro feed (per sezione, ad esempio politica, esteri, sport): usali come esempio di cosa chiedere in un accordo. Per ogni altro editore leggi le condizioni allo stesso modo. Prima di mandare un feed in onda ottieni l\'accordo dell\'editore; l\'URL del feed si aggiunge poi nella scheda Feed.'] },
    { h: 'Controllo del certificato', p: ['Alcuni editori servono i feed con un certificato difettoso. L\'opzione "Ignora controllo certificato" permette a quel solo feed di scaricarsi comunque: la connessione resta cifrata, ma il server non viene verificato. È disattivata di default e pensata solo per feed di cui ti fidi.'] },
    { h: 'Validazione', table: { head: ['Riferimento', 'Cosa verifica', 'Risultato', 'Come rifarla'], rows: [
      ['Test automatici (35)', 'Pulizia del testo, lettura RSS/Atom, allineamento righe/immagini, valori vuoti, rimozione immagini orfane, file invariati, il guasto conserva i vecchi file, pianificatore, avvisi', 'Superati', 'npm test'],
      ['Script Python originale, 2026-10-08, 8 feed reali', 'Stessi titoli e descrizioni dell\'originale per gli stessi feed', '14 file di testo su 16 identici; 2 differiscono perché i feed sono cambiati fra le due esecuzioni (notizie scalate). Un titolo portava un carattere BOM invisibile nell\'originale; la nuova app lo elimina', 'Eseguire entrambi sulla stessa cartella e confrontare'],
      ['Numero di immagini', 'Il numero di immagini per feed coincide con l\'originale', 'Uguale per tutti e 8 i feed', 'Come sopra']] },
      after: ['Non validato: riproduzione in NeMedia Morpheus o in altri sistemi di ticker, percorsi e unità di Windows, funzionamento continuo per giorni, uscita Windows-1252 oltre a un test unitario. Non è uno strumento certificato.'] },
    { h: 'Privacy', p: ['L\'app contatta solo gli indirizzi di feed e immagini che configuri, GitHub (controllo aggiornamenti, facoltativo) e Telegram (solo se lo attivi). Nessuna statistica, nessun account. Impostazioni e log restano su questo computer; il token Telegram è cifrato con il portachiavi del sistema quando disponibile.'] },
    { h: 'Limiti', ul: ['Le immagini sono convertite in JPEG: JPEG, PNG, GIF, BMP e TIFF con una libreria JavaScript, WebP e AVIF con decodificatori WebAssembly (un AVIF molto grande può richiedere qualche secondo). Se la conversione è disattivata in Formato di output, o un\'immagine non si legge, la notizia riceve il segnaposto.', 'Gli indirizzi di immagini sulla rete locale vengono ignorati per i feed su internet pubblico.', 'Il computer deve restare acceso e sveglio; l\'opzione "Tieni il computer sveglio" aiuta.'] }
  ],
  es: [
    { h: 'Qué hace', p: ['Ticker Feed Builder descarga feeds RSS de forma programada y convierte cada feed en un conjunto fijo de archivos para tickers de TV y gráficos de emisión: una línea de texto por titular, una por descripción y un JPG numerado por noticia. La app funciona en la bandeja, 24 horas, y reescribe los archivos cada pocos minutos.'] },
    { h: 'Cómo se usa', ul: ['Crea un perfil. Un perfil es un destino: una carpeta de salida, una lista de feeds y un intervalo de actualización. Usa varios perfiles si pantallas distintas leen carpetas distintas.', 'Elige la carpeta de salida: la que lee tu sistema de ticker o de emisión.', 'Añade feeds (nombre = nombre de carpeta, URL, número de noticias). "Probar" muestra qué contiene el feed sin escribir nada.', 'Pulsa "Ejecutar ahora" una vez y mira la carpeta; luego déjalo funcionando. Al cerrar la ventana la app sigue en la bandeja; para salir usa el menú del icono.'] },
    { h: 'Qué escribe', p: ['Con el formato por defecto, para un feed llamado News:'], table: { head: ['Archivo', 'Contenido'], rows: [['News_Title.Txt', 'Un titular por línea'], ['News_Description.Txt', 'Una descripción por línea, mismo orden'], ['News/00001.JPG, 00002.JPG…', 'Un JPG por noticia, mismo orden'], ['News_metadata.json', 'Contadores de la última ejecución (se puede desactivar)']] } },
    { h: 'Cómo se mantienen sincronizados textos e imágenes', ul: ['La noticia N es siempre la línea N de ambos archivos de texto y la imagen N. Los saltos de línea dentro de un texto se eliminan, así que una noticia nunca ocupa dos líneas.', 'Un título o descripción vacíos pasan a ser el texto "vacío" ("-" por defecto); una imagen ausente o ilegible pasa a ser la imagen de relleno. Los recuentos siempre coinciden.', 'Los archivos se escriben con un nombre temporal y se renombran, así un reproductor nunca lee un archivo a medias. Un archivo cuyo contenido no cambió no se toca.', 'Si un feed no se puede descargar, sus archivos existentes quedan como estaban.', 'Si falta la carpeta de salida (disco desconectado, recurso de red caído) no se escribe nada y la carpeta nunca se crea.'] },
    { h: 'Formatos y NeMedia Morpheus', p: ['La estructura por defecto es la que producían los scripts originales que alimentaban NeMedia Morpheus (nombres de archivo, texto UTF-8, fin de línea LF, nombres JPG de 5 cifras). No hemos leído documentación de NeMedia, así que no está verificada con ella. Otros sistemas de ticker pueden querer otros nombres, codificaciones o tamaños: todo se cambia en "Formato de salida".'] },
    { h: 'Cada cuánto comprueba y qué descarga', ul: ['Cada perfil tiene un intervalo de comprobación (por defecto 5 minutos); un feed puede tener su propio intervalo en la tabla.', 'Una comprobación pregunta primero al servidor si el feed cambió (ETag / Last-Modified); si dice que no, no se descarga nada más. Si el servidor no sabe decirlo, el feed se descarga y se compara con la copia anterior; si es idéntico, no se descargan imágenes y no se toca ningún archivo.', 'Solo si hay algo nuevo se descargan las imágenes y se reescriben los archivos. Si una imagen falló la última vez se reintenta en la siguiente comprobación aunque el feed sea el mismo. Si se borró un archivo de salida o cambiaron los ajustes, el feed se reconstruye.', 'Ejecutar ahora ignora los intervalos y reconstruye todo. El Panel muestra, para cada feed, cuándo se comprobó por última vez y cuándo se actualizaron sus archivos.'] },
    { h: 'Elegir las noticias: filtros, orden, feeds combinados', ul: ['En las Opciones de un feed puedes quedarte solo con las noticias que contengan ciertas palabras, omitir las que contengan otras (mayúsculas y acentos no importan), buscar solo en el título o en título y descripción, quitar noticias con el mismo título y ordenarlas de la más reciente. Los filtros actúan antes del límite: con 10 noticias y algunas filtradas sigues recibiendo 10, si el feed las tiene.', 'Un perfil también puede omitir una noticia ya usada por un feed anterior del mismo perfil (Programación y opciones).', 'Un feed combinado ("+ Añadir feed combinado") junta en una carpeta las últimas noticias de varios feeds del perfil, las más recientes primero y sin duplicados: útil para un ticker mixto de "Últimas noticias". Se reconstruye cuando una de sus fuentes tiene algo nuevo.', 'Probar muestra las noticias exactamente como se escribirían (nombres de archivo, líneas de título y descripción, imagen) y puede mostrar el feed tal cual, sin filtros.'] },
    { h: 'Franjas horarias', p: ['En Programación y opciones un perfil puede comprobarse solo en ciertas horas y días, por ejemplo de 06:00 a 24:00, o cada 2 minutos durante el informativo y cada 15 de noche. Fuera de las franjas no se comprueba nada y los archivos se quedan como están. Desde = Hasta significa todo el día; Desde posterior a Hasta continúa pasada la medianoche. "Ejecutar ahora" siempre funciona.'] },
    { h: 'Feeds parados, resumen y comprobación de archivos', ul: ['Aviso de feed parado: si un feed responde pero no tiene noticias nuevas desde las horas que fijes (por perfil o por feed), recibes un aviso, y otro cuando se recupera. Detecta un ticker que parece bien pero está parado. 0 = desactivado.', 'Resumen diario: a las horas que elijas, un mensaje por los canales activos (Telegram, correo) con feeds OK, problemas y última actualización de cada perfil. "Enviar el resumen ahora" lo prueba. Está desactivado por defecto.', 'Comprobación de archivos: tras escribir, la app relee los archivos y comprueba que los de títulos y descripciones tengan tantas líneas como noticias y que cada imagen sea un JPEG real. Si no, o si un reproductor tiene un archivo abierto y no se puede sustituir, el feed cuenta como fallido y valen las reglas de alertas. Se puede desactivar por perfil.', 'Memoria entre reinicios: la app recuerda cómo era cada feed, así que tras un reinicio un feed sin cambios no se reconstruye y no se vuelve a descargar ninguna imagen. Se puede desactivar en Ajustes.'] },
    { h: 'Modo sin ventana', p: ['El mismo motor puede funcionar sin ventana, para un servidor o un equipo que debe mantener el ticker actualizado tras un reinicio antes de que alguien inicie sesión: exporta los ajustes y arráncalo desde la línea de comandos (los comandos exactos están en Ajustes, sección Modo sin ventana). Usa las mismas programaciones, filtros, alertas (Telegram y correo) y resumen diario. Los secretos no están en el archivo exportado: define TFB_TELEGRAM_TOKEN y TFB_SMTP_PASS en el entorno. En Windows arráncalo con el Programador de tareas al iniciar ("ejecutar tanto si el usuario inició sesión como si no"); en Linux con un servicio systemd. --once ejecuta todo una vez y sale con 0 (todo bien), 1 (un problema) o 2 (ajustes inutilizables).'] },
    { h: 'Alertas', p: ['Como nadie mira la app, ella te avisa: notificación de escritorio, Telegram y/o correo cuando un feed falla varias ejecuciones seguidas, cuando desaparece una carpeta de salida y cuando todo vuelve a funcionar. Telegram y el correo admiten varios destinatarios.', 'Para usar Telegram crea un bot con @BotFather, pon su token en Ajustes y añade los chat ID que deben recibir las alertas. Para el correo introduce servidor SMTP, usuario, contraseña, remitente y los destinatarios (uno por línea); la contraseña se queda en este ordenador, cifrada con el llavero del sistema cuando está disponible, y con usuario la conexión debe ir cifrada. Usa los botones de prueba en Ajustes para comprobar cada canal.', 'Nueva versión: si Telegram o el correo están activos, la app también te avisa una vez por cada nueva release publicada en GitHub (Ajustes, Actualizaciones; comprueba cada 6 horas, incluso con la ventana cerrada). Allí puedes desactivar el aviso.', 'En el panel cada feed muestra sus últimas comprobaciones como pequeñas barras (verde = noticias nuevas, gris = sin cambios, rojo = falló, desde el inicio de la app) y cada perfil dice con palabras si está OK, parcial o con un problema.'] },
    { h: 'Feeds y condiciones de los editores', p: ['Un feed que se descarga libremente no se puede emitir sin más. Los editores suelen ofrecer el RSS para lectura personal; mostrar sus titulares en público en TV, pantallas o webs normalmente requiere un acuerdo con ellos. La responsabilidad es tuya, no de la app, y esto no es asesoramiento legal.', 'La app no incluye feeds. Dos editores cuyas páginas RSS se leyeron el 8 de octubre de 2026 (paráfrasis; lee la página actual antes de fiarte):'], table: { head: ['Editor', 'Qué dice su página RSS', 'Página'], rows: [
      ['ANSA', 'Uso no comercial por particulares y organizaciones sin ánimo de lucro, solo para ver los feeds en programas lectores de RSS. No se permite usarlos para publicar los últimos titulares en webs o blogs. Cualquier otro uso debe solicitarse y autorizarse expresamente.', 'ansa.it/sito/static/ansa_rss.html'],
      ['Adnkronos', 'Uso no comercial por particulares y organizaciones sin ánimo de lucro. Los feeds no pueden hacerse públicos: ni para webs, blogs, sistemas de comunicación exterior u otros medios que difundan las noticias en público, salvo acuerdo previo con Adnkronos.', 'adnkronos.com/rss']] },
      after: ['Ambas páginas listan sus feeds (por sección, por ejemplo política, internacional, deportes): úsalos como ejemplo de qué pedir en un acuerdo. Con cualquier otro editor, lee sus condiciones igual. Antes de emitir un feed, obtén el acuerdo del editor; la URL del feed se añade luego en la pestaña Feeds.'] },
    { h: 'Comprobación del certificado', p: ['Algunos editores sirven feeds con un certificado defectuoso. La opción "Omitir comprobación del certificado" permite que ese feed se descargue igualmente: la conexión sigue cifrada, pero el servidor no se verifica. Está desactivada por defecto y pensada solo para feeds de confianza.'] },
    { h: 'Validación', table: { head: ['Referencia', 'Qué comprueba', 'Resultado', 'Cómo repetirla'], rows: [
      ['Pruebas automáticas (35)', 'Limpieza de texto, lectura RSS/Atom, sincronía líneas/imágenes, valores vacíos, eliminación de imágenes huérfanas, archivos sin cambios, el fallo conserva los archivos antiguos, programador, alertas', 'Superadas', 'npm test'],
      ['Script Python original, 2026-10-08, 8 feeds reales', 'Mismos títulos y descripciones que el original para los mismos feeds', '14 de 16 archivos de texto idénticos; 2 difieren porque los feeds cambiaron entre las dos ejecuciones (noticias desplazadas). Un título llevaba un carácter BOM invisible en el original; la nueva app lo elimina', 'Ejecutar ambos sobre la misma carpeta y comparar'],
      ['Número de imágenes', 'El número de imágenes por feed coincide con el original', 'Igual en los 8 feeds', 'Como arriba']] },
      after: ['No validado: reproducción en NeMedia Morpheus u otros sistemas de ticker, rutas y unidades de Windows, funcionamiento continuo durante días, salida Windows-1252 más allá de una prueba unitaria. No es una herramienta certificada.'] },
    { h: 'Privacidad', p: ['La app solo contacta las direcciones de feeds e imágenes que configuras, GitHub (comprobación de actualizaciones, opcional) y Telegram (solo si lo activas). Sin analíticas ni cuenta. Ajustes y logs se quedan en este ordenador; el token de Telegram se cifra con el llavero del sistema cuando está disponible.'] },
    { h: 'Límites', ul: ['Las imágenes se convierten a JPEG: JPEG, PNG, GIF, BMP y TIFF con una biblioteca JavaScript, WebP y AVIF con decodificadores WebAssembly (un AVIF muy grande puede tardar unos segundos). Si la conversión está desactivada en Formato de salida, o una imagen no se puede leer, la noticia recibe la imagen de relleno.', 'Las direcciones de imágenes de la red local se ignoran en feeds de internet público.', 'El ordenador debe seguir encendido y despierto; la opción "Mantener el ordenador despierto" ayuda.'] }
  ]
};
